name: publish to Dockerhub

on:
  push:
    branches:
      - "master"

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v1

      - name: Install autoconf
        run: |
          sudo apt-get install autoconf

      - name: Docker login
        run: echo '${{ secrets.DOCKER_PWD }}' | docker login --username ${{ secrets.DOCKER_USERNAME }} --password-stdin

      - name: Docker Build
        run: docker build -t zilliz/milvus.io.builder .

      - name: Docker Push lastest
        run: docker push zilliz/milvus.io.builder
